services:
  frankenphp-crud-api:
    container_name: frankenphp-crud-api
    working_dir: /var/www/html
    build: .
    restart: unless-stopped
    ports:
      - "20081:20081"
      - "20444:20444"
    environment:
      - MYSQL_HOST=172.17.0.1
      - MYSQL_PORT=16033
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwerty234*
      - MYSQL_DATABASE=mylog2
      - WEB_SERVER_PORT=20081
      - WEB_SERVER_SSL_PORT=20444
      - TZ=Asia/Jakarta
    #user: "${UID}:${GID}"
    network_mode: bridge